# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locationcode', '__first__'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactive_type', models.CharField(choices=[(b'registration_received', b'Registration received'), (b'registration_confirmed', b'Registration confirmed'), (b'reject_email_messages', b'Reject mail messages'), (b'email_html_template', b'Email HTML template')], max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('from_address', models.EmailField(default=b'piratar@piratar.is', max_length=254)),
                ('subject', models.CharField(default='[P\xedratar] ', max_length=300)),
                ('body', models.TextField()),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['interactive_type', 'added'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveMessageDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=75)),
                ('timing_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('timing_end', models.DateTimeField(null=True)),
                ('interactive_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.InteractiveMessage')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.EmailField(default=b'piratar@piratar.is', max_length=254)),
                ('subject', models.CharField(default='[P\xedratar] ', max_length=300)),
                ('body', models.TextField()),
                ('send_to_all', models.BooleanField(default=True)),
                ('groups_include_subgroups', models.BooleanField(default=True)),
                ('groups_include_locations', models.BooleanField(default=True)),
                ('wasa2il_usage', models.CharField(choices=[(b'any', b'Does not matter'), (b'are_users', b'Recipients are wasa2il users'), (b'not_users', b'Recipients are not wasa2il users')], default=b'any', max_length=12)),
                ('generate_html_mail', models.BooleanField(default=False)),
                ('ready_to_send', models.BooleanField(default=False)),
                ('sending_started', models.DateTimeField(null=True)),
                ('sending_complete', models.DateTimeField(null=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added'],
            },
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('timing_end', models.DateTimeField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message')),
            ],
        ),
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='deliveries',
            field=models.ManyToManyField(related_name='deliveries', through='message.MessageDelivery', to='member.Member'),
        ),
        migrations.AddField(
            model_name='message',
            name='locations',
            field=models.ManyToManyField(blank=True, to='locationcode.LocationCode'),
        ),
        migrations.AddField(
            model_name='message',
            name='membergroups',
            field=models.ManyToManyField(to='member.MemberGroup'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_list',
            field=models.ManyToManyField(related_name='recipient_list', to='member.Member'),
        ),
        migrations.AddField(
            model_name='interactivemessage',
            name='deliveries',
            field=models.ManyToManyField(related_name='interactive_deliveries', through='message.InteractiveMessageDelivery', to='member.Member'),
        ),
    ]
