# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='groups_include_locations',
            field=models.BooleanField(default=False),
        ),
    ]
