# Generated by Django 2.0.13 on 2019-10-19 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190302_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivemessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interactivemessage',
            name='from_address',
            field=models.EmailField(default='piratar@piratar.is', max_length=254),
        ),
        migrations.AlterField(
            model_name='interactivemessage',
            name='interactive_type',
            field=models.CharField(choices=[('registration_received', 'Registration received'), ('registration_confirmed', 'Registration confirmed'), ('reject_email_messages', 'Reject mail messages'), ('email_html_template', 'Email HTML template')], max_length=60),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_address',
            field=models.EmailField(default='piratar@piratar.is', max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='wasa2il_usage',
            field=models.CharField(choices=[('any', 'Does not matter'), ('are_users', 'Recipients are wasa2il users'), ('not_users', 'Recipients are not wasa2il users')], default='any', max_length=12),
        ),
    ]
