# Generated by Django 2.2.13 on 2020-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20200504_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivemessage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
