# Generated by Django 2.2.13 on 2020-09-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20200913_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedelivery',
            name='email',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interactivemessage',
            name='interactive_type',
            field=models.CharField(choices=[('registration_received', 'Registration received'), ('registration_confirmed', 'Registration confirmed'), ('reject_email_messages', 'Reject mail messages'), ('email_html_template', 'Email HTML template'), ('mailinglist_confirmation', 'Mailing list confirmation'), ('remind_membership', 'Reminder of existing membership')], max_length=60),
        ),
        migrations.AlterField(
            model_name='messagedelivery',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member'),
        ),
    ]
