# Generated by Django 2.2.13 on 2020-09-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_remove_message_wasa2il_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='groups_include_locations',
        ),
        migrations.RemoveField(
            model_name='message',
            name='locations',
        ),
    ]
