# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20180117_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivemessage',
            name='from_address',
            field=models.EmailField(default=b'piratar@piratar.is', max_length=254),
        ),
        migrations.AlterField(
            model_name='interactivemessage',
            name='subject',
            field=models.CharField(default='[P\xedratar] ', max_length=300),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_address',
            field=models.EmailField(default=b'piratar@piratar.is', max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='[P\xedratar] ', max_length=300),
        ),
    ]
