# Generated by Django 2.2.13 on 2020-10-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20200930_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactivemessage',
            name='deliveries',
        ),
        migrations.DeleteModel(
            name='InteractiveMessageDelivery',
        ),
    ]
