# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20190225_1928'),
        ('message', '0009_auto_20180521_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='membergroups',
            field=models.ManyToManyField(to='member.MemberGroup'),
        ),
    ]
