# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_message_membergroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='groups',
        ),
    ]
