# Generated by Django 2.2.13 on 2020-10-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20200930_1735'),
        ('message', '0010_auto_20201006_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagedelivery',
            old_name='timing_start',
            new_name='timing',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deliveries',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient_list',
        ),
        migrations.RemoveField(
            model_name='messagedelivery',
            name='email',
        ),
        migrations.RemoveField(
            model_name='messagedelivery',
            name='timing_end',
        ),
        migrations.AddField(
            model_name='message',
            name='include_mailing_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_count_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Subscriber'),
        ),
        migrations.AlterField(
            model_name='message',
            name='membergroups',
            field=models.ManyToManyField(related_name='messages', to='member.MemberGroup'),
        ),
        migrations.AlterField(
            model_name='messagedelivery',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AlterField(
            model_name='messagedelivery',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='message.Message'),
        ),
    ]
