# Generated by Django 2.2.13 on 2020-10-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_auto_20201010_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactivemessage',
            name='active',
        ),
    ]
