# Generated by Django 2.2.13 on 2020-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_remove_interactivemessage_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='being_processed',
            field=models.BooleanField(default=False),
        ),
    ]
