# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionevent',
            old_name='affected_members',
            new_name='affected_members_deprecated',
        ),
        migrations.AddField(
            model_name='actionevent',
            name='affected_member_ids',
            field=models.TextField(default=''),
        ),
    ]
