# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-23 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190723_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionevent',
            name='affected_members_deprecated',
        ),
    ]
