# Generated by Django 2.2.13 on 2020-10-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_actionevent_affected_members_deprecated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionEvent',
        ),
    ]
