# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 22:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationcode', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=63)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_unwanted', models.BooleanField(default=False)),
                ('email_wanted', models.NullBooleanField(default=None)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('verified', models.BooleanField(default=False)),
                ('auth_token', models.CharField(max_length=100, null=True, unique=True)),
                ('auth_timing', models.DateTimeField(null=True)),
                ('legal_name', models.CharField(max_length=63)),
                ('legal_address', models.CharField(max_length=63)),
                ('legal_zip_code', models.CharField(max_length=3, null=True)),
                ('legal_municipality_code', models.CharField(max_length=5, null=True)),
                ('legal_zone', models.CharField(max_length=63, null=True)),
                ('legal_lookup_timing', models.DateTimeField(null=True)),
                ('temporary_web_id', models.CharField(max_length=40, null=True, unique=True)),
                ('temporary_web_id_timing', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['added', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('techname', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('combination_method', models.CharField(choices=[(b'union', b'Union'), (b'intersection', b'Intersection')], default=b'union', max_length=30, verbose_name=b'Combination method')),
                ('auto_locations', models.ManyToManyField(related_name='auto_location_membergroups', to='locationcode.LocationCode')),
                ('auto_subgroups', models.ManyToManyField(related_name='auto_parent_membergroups', to='member.MemberGroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='membergroups',
            field=models.ManyToManyField(related_name='members', to='member.MemberGroup'),
        ),
    ]
