# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membergroup',
            name='admins',
            field=models.ManyToManyField(related_name='membergroup_administrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
