# Generated by Django 2.2.13 on 2020-09-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membergroup',
            name='auto_locations',
        ),
        migrations.RemoveField(
            model_name='membergroup',
            name='combination_method',
        ),
    ]
