# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_email_wanted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email_wanted',
            field=models.NullBooleanField(default=None),
        ),
    ]
