# Generated by Django 2.2.17 on 2021-01-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20201025_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='membergroup',
            name='condition_municipalities',
            field=models.ManyToManyField(related_name='membergroup_conditions', to='member.Municipality'),
        ),
    ]
