# Generated by Django 2.2.24 on 2021-09-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_membergroup_condition_municipalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_wanted_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email_wanted_timing',
            field=models.DateTimeField(null=True),
        ),
    ]
