# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20180525_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='member',
            name='partake',
        ),
    ]
