# Generated by Django 2.2.27 on 2022-03-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20210908_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DateTimeField(auto_now_add=True)),
                ('member_count', models.IntegerField()),
            ],
            options={
                'ordering': ['timing'],
            },
        ),
    ]
