# Generated by Django 2.2.27 on 2022-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_memberstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberstat',
            name='timing',
            field=models.DateTimeField(),
        ),
    ]
