# Generated by Django 3.2.23 on 2023-12-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20220317_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email_wanted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
