# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20190225_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='groups',
        ),
    ]
